-- Add new enum values to OrderStatus
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'WAITING_CONFIRMATION';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'DONE';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
